name: Build Flatpak for Linux x64

on: 
    workflow_dispatch: 
    push:
        branches: 
            - '**'

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                config:
                    - name: Flatpak Linux (x64)
                      os: ubuntu-latest
                    
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Get .NET 8
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.300'

            - name: Get Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.7' 
            
            - name: Update packages and get Flatpak & Flatpak Builder
              run: sudo apt-get update && sudo apt-get install -y flatpak flatpak-builder
            
            - name: Install Flathub Repo
              run: flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
            
            - name: Restore Flatpak cache
              uses: actions/cache@v3
              with:
                path: |
                  ~/.local/share/flatpak/repo
                  ~/.local/share/flatpak/runtime

            - name: Install Flatpak dependencies (first round)
              run: ./FlatpakScripts/install_flatpak_dependencies.sh
              shell: bash
          
            - name: Generate NuGet sources
              run: ./FlatpakScripts/generate_nuget_sources.sh
              shell: bash
            
            - name: Install Flatpak dependencies (repeat)
              run: ./FlatpakScripts/install_flatpak_dependencies.sh
              shell: bash
            
            - name: Build and install Flatpak
              run: ./FlatpakScripts/build_and_install.sh
              shell: bash
            
            - name: Bundle the app
              run: flatpak build-bundle repo gdpad.net.flatpak org.gdpad.dotnet --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

            - uses: actions/upload-artifact@v4
              with:
                name: GDPadDotnet Flatpak Bundle
                path: gdpad.net.flatpak
